server:
  port: 8080

spring:
  application:
    name: bff
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ENTRA_ISSUER_URI}
          audiences:
            - ${ENTRA_API_CLIENT_ID}

microservices:
  clientes:
    base-url: http://localhost:8081
  catalogo:
    base-url: http://localhost:8082

